import { TextToSpeechClient } from '@google-cloud/text-to-speech';

let client: TextToSpeechClient | null = null;

// Tiny 1-second silent MP3 frame base64 string to allow testing/dev without GCloud credentials
const SILENT_MP3_BASE64 = 
  '//uQxAAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAACAAACQACAAAAAAP/hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADpMYW1lMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV' +
  'VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV' +
  'VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/6EMQAH//+QZAAf//5AAAAAP/4QAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/+hDEAB///kGQAH//+QAAAAD/+E' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//uQxAAf//5BkAB///kAAAAAD/+EAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';

function getTtsClient(): TextToSpeechClient | null {
  if (client) return client;

  // Production: base64-encoded JSON (avoids shell escaping issues in CI/CD)
  // Local dev: raw JSON in GOOGLE_APPLICATION_CREDENTIALS_JSON
  let credentialsJson: string | undefined;

  const b64 = process.env.GOOGLE_APPLICATION_CREDENTIALS_B64;
  if (b64) {
    credentialsJson = Buffer.from(b64, 'base64').toString('utf-8');
  } else {
    credentialsJson = process.env.GOOGLE_APPLICATION_CREDENTIALS_JSON;
  }

  if (!credentialsJson) {
    console.warn('[GoogleTTS] No se encontró credencial (GOOGLE_APPLICATION_CREDENTIALS_B64 ni GOOGLE_APPLICATION_CREDENTIALS_JSON).');
    return null;
  }

  try {
    const credentials = JSON.parse(credentialsJson);
    client = new TextToSpeechClient({ credentials });
    return client;
  } catch (error) {
    console.error('[GoogleTTS] Error al inicializar el cliente de Google Cloud TTS:', error);
    return null;
  }
}

/**
 * Genera un buffer de audio MP3 a partir de texto usando Google Cloud TTS.
 * Si las credenciales no están presentes en desarrollo o tests, retorna un buffer silencioso.
 */
export async function generateTtsAudio(text: string): Promise<Buffer> {
  if (!text || !text.trim()) {
    throw new Error('El texto no puede estar vacío');
  }

  const ttsClient = getTtsClient();

  if (!ttsClient) {
    const isProd = process.env.NODE_ENV === 'production';
    if (isProd) {
      throw new Error('Servicio de Google Cloud TTS no configurado en producción');
    }
    console.warn('[GoogleTTS] Retornando audio silencioso de prueba (modo desarrollo).');
    return Buffer.from(SILENT_MP3_BASE64, 'base64');
  }

  const [response] = await ttsClient.synthesizeSpeech({
    input: { text },
    voice: {
      languageCode: 'es-US',
      name: 'es-US-Neural2-C', // Spanish neural voice
      ssmlGender: 'MALE',
    },
    audioConfig: {
      audioEncoding: 'MP3',
      speakingRate: 1.0,
      pitch: 0.0,
    },
  });

  const audioContent = response.audioContent;
  if (!audioContent) {
    throw new Error('No se recibió contenido de audio desde la API de Google TTS');
  }

  return Buffer.from(audioContent as Uint8Array);
}
